### ISSUE TITLE
不知道怎么回事，所有的onGetResponseSuccess会执行两边

### ISSUE THREAD

**Issue by beiguancyc** [aoenang/seny-devpkg#3]
设置好监听后都会执行两次。

**Comment by aoenang** [comment]
发请求的get方法，最后一个参数是isCache，默认true。先读缓存，再读服务器

**Comment by beiguancyc** [comment]
感谢您的回复，调试时发现是这个原因了。后来经过测试，发现如果只要存在过缓存，isCache无论true或false都会读取缓存。

if (method == Request.Method.GET) {
                tryLoadCacheResponse(request, requestCode, listener);
            }
我自己在这里加了isCache的判断。

**Comment by aoenang** [comment]
这个参数是指是否缓存本次响应数据。而网络请求逻辑是只要有缓存就会读，先满足界面显示，然后再请求网络上的新数据更新一次。如果自己有特殊需求，可以再修改一下
